server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://database-user-service.cleqaiyiopvh.ap-south-1.rds.amazonaws.com:3306/usersdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: jabtakhaijan

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://3.110.128.197:8761/eureka